#!/usr/bin/env ruby

def want_to_deploy?
  true
end

def handle_deploy
  current_branch = `git rev-parse --abbrev-ref HEAD`.chomp!

  case current_branch
  when 'master'
    `bundle exec rake deploy`
  else
    puts 'Not on master.'
  end if want_to_deploy?
end

case ARGV.join(' ')
when "-h"
  puts "Deploys using Mina when on either 'develop'."
else
  handle_deploy
end

